services:
  app:
    container_name: vkbot
    image: "vavlxxx/vk-bot"
    build:
      context: .
    env_file:
      - ".env"
    command: "poetry run python ./src/main.py"
    volumes:
      - ./logs:/app/logs
      - ./bot.db:/app/bot.db

